<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.jobportal</groupId>
    <artifactId>job-portal-parent</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>

    <modules>
        <module>Eureka-Server</module>
        <module>Api-Gateway</module>
        <module>Auth-Service</module>
        <module>Profile-Service</module>
        <module>Job-Service</module>
        <module>Application-Service</module>
        <module>Interview-Service</module>
        <module>Subscription-Service</module>
        <module>Notification-Service</module>
        <module>Analytics-Service</module>
        <module>JobPortal-Web</module>
    </modules>
</project>