spring.application.name=Api-Gateway
spring.application.key=vghjgyufx3456786e$#%^#ERDTFGtghbvh
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# AUTH SERVICE
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1

# PROFILE SERVICE
spring.cloud.gateway.routes[1].id=profile-service
spring.cloud.gateway.routes[1].uri=lb://PROFILE-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/users/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1

# JOB SERVICE
spring.cloud.gateway.routes[2].id=job-service
spring.cloud.gateway.routes[2].uri=lb://JOB-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/jobs/**
spring.cloud.gateway.routes[2].filters[0]=StripPrefix=1

# Application SERVICE
spring.cloud.gateway.routes[3].id=application-service
spring.cloud.gateway.routes[3].uri=lb://APPLICATION-SERVICE
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/application/**
spring.cloud.gateway.routes[3].filters[0]=StripPrefix=1

# Interview SERVICE
spring.cloud.gateway.routes[4].id=interview-service
spring.cloud.gateway.routes[4].uri=lb://INTERVIEW-SERVICE
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/interview/**
spring.cloud.gateway.routes[4].filters[0]=StripPrefix=1