spring.application.name=Api-Gateway
server.port=8080

spring.main.web-application-type=reactive
spring.application.key=${JWT_SECRET}

eureka.client.service-url.defaultZone=${EUREKA_URL:http://eureka-server:8761/eureka/}
eureka.instance.prefer-ip-address=true

# LOAD BALANCER
spring.cloud.loadbalancer.retry.enabled=true
# TIMEOUTS
spring.cloud.gateway.httpclient.connect-timeout=5000
spring.cloud.gateway.httpclient.response-timeout=10s
# ACTUATOR
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
# LOGGING (DEBUGGING)
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.reactor.netty=INFO

# ROUTES
# AUTH SERVICE
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://auth-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1

# PROFILE SERVICE
spring.cloud.gateway.routes[1].id=profile-service
spring.cloud.gateway.routes[1].uri=lb://profile-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/users/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1

# JOB SERVICE
spring.cloud.gateway.routes[2].id=job-service
spring.cloud.gateway.routes[2].uri=lb://job-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/jobs/**
spring.cloud.gateway.routes[2].filters[0]=StripPrefix=1

# APPLICATION SERVICE
spring.cloud.gateway.routes[3].id=application-service
spring.cloud.gateway.routes[3].uri=lb://application-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/application/**
spring.cloud.gateway.routes[3].filters[0]=StripPrefix=1

# INTERVIEW SERVICE
spring.cloud.gateway.routes[4].id=interview-service
spring.cloud.gateway.routes[4].uri=lb://interview-service
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/interview/**
spring.cloud.gateway.routes[4].filters[0]=StripPrefix=1

# SUBSCRIPTION SERVICE
spring.cloud.gateway.routes[5].id=subscription-service
spring.cloud.gateway.routes[5].uri=lb://subscription-service
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/subscription/**
spring.cloud.gateway.routes[5].filters[0]=StripPrefix=1

# NOTIFICATION SERVICE
spring.cloud.gateway.routes[6].id=notification-service
spring.cloud.gateway.routes[6].uri=lb://notification-service
spring.cloud.gateway.routes[6].predicates[0]=Path=/api/notifications/**
spring.cloud.gateway.routes[6].filters[0]=StripPrefix=1

# ANALYTICS SERVICE
spring.cloud.gateway.routes[7].id=analytics-service
spring.cloud.gateway.routes[7].uri=lb://analytics-service
spring.cloud.gateway.routes[7].predicates[0]=Path=/api/analytics/**
spring.cloud.gateway.routes[7].filters[0]=StripPrefix=1

# WEBSOCKET (NOTIFICATION SERVICE)
spring.cloud.gateway.routes[8].id=notification-ws
spring.cloud.gateway.routes[8].uri=lb:ws://notification-service
spring.cloud.gateway.routes[8].predicates[0]=Path=/api/notifications/ws-notifications/**
spring.cloud.gateway.routes[8].filters[0]=StripPrefix=1
spring.cloud.gateway.routes[8].order=1

# FRONTEND (STATIC)
spring.cloud.gateway.routes[9].id=jobportal-web
spring.cloud.gateway.routes[9].uri=lb://jobportal-web
spring.cloud.gateway.routes[9].predicates[0]=Path=/,/*.html,/assets/**,/static/**
spring.cloud.gateway.routes[9].order=100

# SWAGGER ROUTES
spring.cloud.gateway.routes[10].id=auth-docs
spring.cloud.gateway.routes[10].uri=lb://auth-service
spring.cloud.gateway.routes[10].predicates[0]=Path=/auth/api-docs/**
spring.cloud.gateway.routes[10].filters[0]=RewritePath=/auth/api-docs,/api-docs

spring.cloud.gateway.routes[11].id=job-docs
spring.cloud.gateway.routes[11].uri=lb://job-service
spring.cloud.gateway.routes[11].predicates[0]=Path=/job/api-docs/**
spring.cloud.gateway.routes[11].filters[0]=RewritePath=/job/api-docs,/api-docs

spring.cloud.gateway.routes[12].id=profile-docs
spring.cloud.gateway.routes[12].uri=lb://profile-service
spring.cloud.gateway.routes[12].predicates[0]=Path=/profile/api-docs/**
spring.cloud.gateway.routes[12].filters[0]=RewritePath=/profile/api-docs,/api-docs

spring.cloud.gateway.routes[13].id=application-docs
spring.cloud.gateway.routes[13].uri=lb://application-service
spring.cloud.gateway.routes[13].predicates[0]=Path=/application/api-docs/**
spring.cloud.gateway.routes[13].filters[0]=RewritePath=/application/api-docs,/api-docs

spring.cloud.gateway.routes[14].id=analytics-docs
spring.cloud.gateway.routes[14].uri=lb://analytics-service
spring.cloud.gateway.routes[14].predicates[0]=Path=/analytics/api-docs/**
spring.cloud.gateway.routes[14].filters[0]=RewritePath=/analytics/api-docs,/api-docs

spring.cloud.gateway.routes[15].id=interview-docs
spring.cloud.gateway.routes[15].uri=lb://interview-service
spring.cloud.gateway.routes[15].predicates[0]=Path=/interview/api-docs/**
spring.cloud.gateway.routes[15].filters[0]=RewritePath=/interview/api-docs,/api-docs

spring.cloud.gateway.routes[16].id=notification-docs
spring.cloud.gateway.routes[16].uri=lb://notification-service
spring.cloud.gateway.routes[16].predicates[0]=Path=/notification/api-docs/**
spring.cloud.gateway.routes[16].filters[0]=RewritePath=/notification/api-docs,/api-docs

spring.cloud.gateway.routes[17].id=subscription-docs
spring.cloud.gateway.routes[17].uri=lb://subscription-service
spring.cloud.gateway.routes[17].predicates[0]=Path=/subscription/api-docs/**
spring.cloud.gateway.routes[17].filters[0]=RewritePath=/subscription/api-docs,/api-docs

# SWAGGER UI
springdoc.swagger-ui.path=/swagger-ui.html

springdoc.swagger-ui.urls[0].name=Auth Service
springdoc.swagger-ui.urls[0].url=/auth/api-docs

springdoc.swagger-ui.urls[1].name=Job Service
springdoc.swagger-ui.urls[1].url=/job/api-docs

springdoc.swagger-ui.urls[2].name=Profile Service
springdoc.swagger-ui.urls[2].url=/profile/api-docs

springdoc.swagger-ui.urls[3].name=Application Service
springdoc.swagger-ui.urls[3].url=/application/api-docs

springdoc.swagger-ui.urls[4].name=Analytics Service
springdoc.swagger-ui.urls[4].url=/analytics/api-docs

springdoc.swagger-ui.urls[5].name=Interview Service
springdoc.swagger-ui.urls[5].url=/interview/api-docs

springdoc.swagger-ui.urls[6].name=Notification Service
springdoc.swagger-ui.urls[6].url=/notification/api-docs

springdoc.swagger-ui.urls[7].name=Subscription Service
springdoc.swagger-ui.urls[7].url=/subscription/api-docs