spring.application.name=Profile-service
server.port=8082
spring.datasource.url=jdbc:postgresql://localhost:5432/job-portal-profile
spring.datasource.username=postgres
spring.datasource.password=0000
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.application.token.expiry=3600
spring.application.key=

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html